### PR TITLE
Remove hardcoded response type which blocks response body in the case…

### LINKED ISSUE #6: Hardcoded response type blocks response body in the case of server error
Currently the response type is hardcoded as "json". If the server returns response of different type, typically in te case of server error, parsing fails and we get null response body.

It would be better not to set response type and leave parsing the response to the api user.

I wonder if doing this would break processing in the non-error case.. can somebody comment?

I can do a pull request  if this change is deemed correct.

### PR DESCRIPTION
**Pull request by martinvlk**
… of server error.

Fixes #6

### CODE REVIEW

**Comment by smurphy8** [comment]
@msewell17 can you check this against IE9 and things tomorrow?  If it doesn't seem to break anything we will add it.

**Comment by msewell17** [comment]
Sounds good

**Comment by msewell17** [comment]
@martinvlk I tested these changes with a wide variety of routes and browser combinations. 

The only blip I found was when the response body is null in IE9, the response is interpreted as a ServantError even when the server outputs a 200 OK

**Comment by martinvlk** [comment]
Okay, let me fix that.. though I don't have IE9, so for testing I'l ask you @msewell17 to check it out.

**Comment by msewell17** [comment]
@martinvlk sounds good

**Comment by mchaver** [comment]
@martinvlk
Did you ever get a chance to complete this?

**Comment by martinvlk** [comment]
Er, nope - a lot's happenned since then and I couldn't complete this. And I won't be able to either, in foreseeable future, sorry.

MV

**Pull request closed without merging**
