### PR TITLE
Changed BaseURI to Maybe BaseUri to simplify deployment in browser.

### PR DESCRIPTION
**Pull request by ondrap**
This addresses issue  #2 . I know it's not backward compatibile, but it seems to me it makes things much simpler in terms of app development. (sorry for the fixed spaces, the Atom editr seem to fix this automatically).

### CODE REVIEW

**Comment by ondrap** [comment]
I wanted to do the second commit as a separate Pull request, but didn't know how it works on GitHub. Anyway, the `undefined` in the ServantError causes Prelude.undefined error when you try to `Show` the error; that should not generally happen.

**Comment by smurphy8** [comment]
I will try to get some time together to look this over tomorrow.  Thanks

**Comment by ondrap** [comment]
Have you had a look? Any comments/ideas?

**Comment by msewell17** [comment]
@ondrap sorry it's been awhile since I have been working on my ghcjs project. Today with a few changes I was able to build my project with your changes to this library. I am going to merge them into dev_improved_base and also into master. After that, the master and dev_improved_base branches will be completely the same. I'll likely delete the dev_improved_base branch soon because most other ghcjs packages use master as the improved base branch since improved-base took over.

**Comment by msewell17** [comment]
@ondrap getting rid of the undefined's was very helpful. I knew there was a problem with displaying servant errors but I hadn't tracked down the bug. Thank you. And the BaseUrl -> Maybe BaseUrl seemed like a good improvement with very little drawback

**Pull request merged**
